#Hugo configuration
title = "This"
baseURL = "https:\/\/thiss.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758904"
subfolder = ""
cookiedomain = ""
